### ISSUE TITLE
Win32 reference not included

### ISSUE THREAD

**Issue by shalzuth** [H4NM/WhoYouCalling#8]
The 2 classes/files in WhoYouCalling.Win32 namespace are not included.
I think it's an issue with your .gitignore if you have those files in a folder called Win32 - maybe call it a different folder name or change the gitignore.

**Comment by H4NM** [comment]
Found the culprit: https://github.com/H4NM/WhoYouCalling/blob/85092635d9ebfc459d13be1dddaf6952a3aa30b6/.gitignore#L42

I've excluded the regex line and added a forced include of all source code that will be included in next merge.
Thanks for reporting!
